name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Roguelike Jak 2"
      metadataDescription: "The Jak Time Loop is broken! To restore it, Jak must fight through random missions that grow more unstable the further you venture. As the enemies get stronger, so can you! With Vin's help, Jak must blast his way back into the metalhead nest, and restore his destiny."
      metadataSupportedGames: "jak2"
      metadataAuthors: "Kraken"
      metadataTags: "rng,gameplay-mod,challenge"
      metadataWebsiteUrl: "https://github.com/RealOfficialKraken/roguelikejakii"
      skipMacOS: true
      skipLinux: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "game/assets"
      copyEntireBinaryDir: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
